### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by marschaeffer** [codeBelt/react-redux-architecture#25]
I am getting an error, not sure what is wrong. 
Can sb help?

```
>node --version
v13.9.0

>npm --version
6.14.1

>npm start

> react-typescript@0.1.0 start f:\GIT\react-redux-architecture
> cross-env CLIENT_ENV=development craco start

Starting the development server...

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:118:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (f:\GIT\react-redux-architecture\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (f:\GIT\react-redux-architecture\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (f:\GIT\react-redux-architecture\node_modules\express\lib\router\index.js:317:13)
    at f:\GIT\react-redux-architecture\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (f:\GIT\react-redux-architecture\node_modules\express\lib\router\index.js:335:12)
    at next (f:\GIT\react-redux-architecture\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (f:\GIT\react-redux-architecture\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (f:\GIT\react-redux-architecture\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (f:\GIT\react-redux-architecture\node_modules\express\lib\router\index.js:317:13)
    at f:\GIT\react-redux-architecture\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (f:\GIT\react-redux-architecture\node_modules\express\lib\router\index.js:335:12)
    at next (f:\GIT\react-redux-architecture\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (f:\GIT\react-redux-architecture\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (f:\GIT\react-redux-architecture\node_modules\express\lib\router\layer.js:95:5)

```

**Comment by codeBelt** [comment]
@marschaeffer I cannot reproduce your issue. Are you on a Mac?

I update all the packages to the latest versions so pull down the latest and give it another try. 

Other than that I don't know how to help you.

**Comment by marschaeffer** [comment]
Reinstalled everything, build and started with yarn .. now it is working. 
Thanks for this project!
